### ISSUE TITLE
Fire widget, very much needed

### ISSUE THREAD

**Issue by nannerpusser** [JohnDevlopment/CTkTreeview#1]
Based widget extension right here :shipit:  💯 

I'm terrible with python, but CTk and stuff like sv-ttk keeps me hacking away at dumb projects, but my biggest/current project requires a TreeView + scrollbar  as 1/3 of my main interface window and of course, CustomTkinter is basically 100% backwards compatible with ttk except for a damn TreeView widget. This is great stuff here and maybe you can even eventually submit to official CustomTkinter for future inclusion. 🦄

**Comment by JohnDevlopment** [comment]
Thanks!
